### PR TITLE
adding confirmation before reset

### LINKED ISSUE #8: Ask for confirmation before resetting the board
Pressing R resets the game. Since this may be triggered by accident, we should ask the user for confirmation before resetting the game.

### PR DESCRIPTION
**Pull request by jylee14**
fix #8 by adding stdweb::web::confirm 

as a side note, 
I found this on the rust subreddit, 
this is my first contribution to an open source project. Please let me know if there is a better way to go about opening PR or documenting changes, etc 
thank you :)

### CODE REVIEW

**Comment by BartMassey** [comment]
This looks great and seems to work fine — thanks much!

Before we merge this pull request, it would be nice if you would add whitespace at the `if` and `else` to match standard Rust formatting. You should be able to use `git commit --amend` to merge this change, and `git push --force` to update the pull request. Let us know if you have issues and we can help you out.

Really appreciate your participation here.

**Comment by jylee14** [comment]
I made the changes. 
Thank you for your comments

**Comment by BartMassey** [comment]
Well shoot. I thought I had write access to this repo, but I guess I don't. We'll wait for @KappaDistributive to merge this.

Again, thanks much for your contribution!

**Comment by KappaDistributive** [comment]
Thanks for your contribution @jylee14 and thanks for the review @BartMassey

**Pull request merged**
